# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtag',
            field=models.ManyToManyField(to='feed.HashTag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('dv', 'Development'), ('ps', 'Personal')], default='dv', max_length=2),
        ),
    ]
